--File generated by vm/make.lua
--[[This file is part of Plume
Plume🪶 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.
Plume🪶 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Plume🪶.
If not, see <https://www.gnu.org/licenses/>.
]]
return function (plume)
    function plume.run(chunk, parameters)
        local empty=plume.obj.empty
        local ptable=plume.obj.table
        local function _type(x)
            local t=type(x)
            if t=="table" then
                if x==empty then
                    return "empty"
                else
                    return x.type or x[1]
                end
            else
                return t
            end
        end
        local bit=require("bit")
        local OP_BITS=7
        local ARG1_BITS=5
        local ARG2_BITS=20
        local ARG1_SHIFT=ARG2_BITS
        local OP_SHIFT=ARG1_BITS + ARG2_BITS
        local MASK_OP=bit.lshift(1, OP_BITS) - 1
        local MASK_ARG1=bit.lshift(1, ARG1_BITS) - 1
        local MASK_ARG2=bit.lshift(1, ARG2_BITS) - 1
        require("table.new")
        local bytecode=chunk.bytecode
        local constants=chunk.constants
        local static=chunk.static
        local ip=0
        local tic=0
        local ms=table.new(2^14, 0)
        local msf=table.new(2^8, 0)
        local msp=0
        local msfp=0
        local vs=table.new(2^10, 0)
        local vsf=table.new(2^8, 0)
        local vsp=0
        local vsfp=0
        local jump=0
        local instr, op, arg1, arg2=0, 0, 0, 0
        local hook=plume.hook
        if parameters then
            if chunk.isFile then
                for k, v in pairs(parameters) do
                    local offset=chunk.namedParamOffset[k]
                    if offset then
                        chunk.static[offset]=v
                    end
                end
            else
                for i=1, chunk.localsCount do
                    if parameters[i]==nil then
                        vs[i]=empty
                    else
                        vs[i]=parameters[i]
                    end
                end
                vsp=chunk.localsCount
                vsfp=1
                table.insert(vsf, 1)
            end
        end
        ::DISPATCH::
                	if hook then
        if ip>0 then
            hook(
                chunk,
                tic, ip, jump,
                instr, op, arg1, arg2,
                ms, msp, msf, msfp,
                vs, vsp, vsf, vsfp
            )
        end
    end
    if jump>0 then
        ip=jump
        jump=0
    else
        ip=ip+1
    end
    tic=tic+1
                instr=bytecode[ip]
    op=bit.band(bit.rshift(instr, OP_SHIFT), MASK_OP)
    arg1=bit.band(bit.rshift(instr, ARG1_SHIFT), MASK_ARG1)
    arg2=bit.band(instr, MASK_ARG2)
            			if op==1 then goto LOAD_CONSTANT
			elseif op==2 then goto LOAD_TRUE
			elseif op==3 then goto LOAD_FALSE
			elseif op==4 then goto LOAD_EMPTY
			elseif op==5 then goto LOAD_LOCAL
			elseif op==6 then goto LOAD_LEXICAL
			elseif op==7 then goto LOAD_STATIC
			elseif op==8 then goto STORE_LOCAL
			elseif op==9 then goto STORE_LEXICAL
			elseif op==10 then goto STORE_STATIC
			elseif op==11 then goto STORE_VOID
			elseif op==12 then goto TABLE_NEW
			elseif op==13 then goto TABLE_ADD
			elseif op==14 then goto TABLE_SET
			elseif op==15 then goto TABLE_INDEX
			elseif op==16 then goto TABLE_INDEX_ACC_SELF
			elseif op==17 then goto TABLE_SET_META
			elseif op==18 then goto TABLE_INDEX_META
			elseif op==19 then goto TABLE_SET_ACC
			elseif op==20 then goto TABLE_SET_ACC_META
			elseif op==21 then goto TABLE_EXPAND
			elseif op==22 then goto ENTER_SCOPE
			elseif op==23 then goto LEAVE_SCOPE
			elseif op==24 then goto ENTER_FILE
			elseif op==25 then goto LEAVE_FILE
			elseif op==26 then goto BEGIN_ACC
			elseif op==27 then goto ACC_TABLE
			elseif op==28 then goto ACC_TEXT
			elseif op==29 then goto ACC_EMPTY
			elseif op==30 then goto ACC_CALL
			elseif op==31 then goto RETURN
			elseif op==32 then goto ACC_CHECK_TEXT
			elseif op==33 then goto JUMP_IF
			elseif op==34 then goto JUMP_IF_NOT
			elseif op==35 then goto JUMP_IF_NOT_EMPTY
			elseif op==36 then goto JUMP
			elseif op==37 then goto JUMP_IF_PEEK
			elseif op==38 then goto JUMP_IF_NOT_PEEK
			elseif op==39 then goto GET_ITER
			elseif op==40 then goto FOR_ITER
			elseif op==41 then goto OPP_ADD
			elseif op==42 then goto OPP_MUL
			elseif op==43 then goto OPP_SUB
			elseif op==44 then goto OPP_DIV
			elseif op==45 then goto OPP_NEG
			elseif op==46 then goto OPP_MOD
			elseif op==47 then goto OPP_POW
			elseif op==48 then goto OPP_GTE
			elseif op==49 then goto OPP_LTE
			elseif op==50 then goto OPP_GT
			elseif op==51 then goto OPP_LT
			elseif op==52 then goto OPP_EQ
			elseif op==53 then goto OPP_NEQ
			elseif op==54 then goto OPP_AND
			elseif op==55 then goto OPP_NOT
			elseif op==56 then goto OPP_OR
			elseif op==57 then goto DUPLICATE
			elseif op==58 then goto SWITCH
			elseif op==59 then goto END
			end
            			::LOAD_CONSTANT::
	do
	    msp=msp+1
	    ms[msp]=constants[arg2]
				goto DISPATCH
end
			::LOAD_TRUE::
	do
	    msp=msp+1
	    ms[msp]=true
				goto DISPATCH
end
			::LOAD_FALSE::
	do
	    msp=msp+1
	    ms[msp]=false
				goto DISPATCH
end
			::LOAD_EMPTY::
	do
	    msp=msp+1
	    ms[msp]=empty
				goto DISPATCH
end
			::LOAD_LOCAL::
	do
	    msp=msp+1
	    ms[msp]=vs[vsf[vsfp] + arg2-1]
				goto DISPATCH
end
			::LOAD_LEXICAL::
	do
	    msp=msp+1
	    ms[msp]=vs[vsf[vsfp-arg1]+arg2-1]
				goto DISPATCH
end
			::LOAD_STATIC::
	do
	    msp=msp+1
	    ms[msp]=static[arg2]
				goto DISPATCH
end
			::STORE_LOCAL::
	do
	    vs[vsf[vsfp] + arg2-1]=ms[msp]
	    msp=msp-1
				goto DISPATCH
end
			::STORE_LEXICAL::
	do
	    vs[vsf[vsfp-arg1]+arg2-1]=ms[msp]
	    msp=msp-1
				goto DISPATCH
end
			::STORE_STATIC::
	do
	    static[arg2]=ms[msp]
	    msp=msp-1
				goto DISPATCH
end
			::STORE_VOID::
	do
	    msp=msp-1
				goto DISPATCH
end
			::TABLE_NEW::
	do
	    msp=msp + 1
	    ms[msp]=table.new(0, arg1)
				goto DISPATCH
end
			::TABLE_ADD::
	do
				goto DISPATCH
end
			::TABLE_SET::
	do
	    local t=ms[msp]
	    local key=ms[msp-1]
	    local value=ms[msp-2]
	    if not t.table[key] then
	        table.insert(t.keys, key)
	        if t.meta.table.setindex then
	            local meta=t.meta.table.setindex
	            local params={key, value}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            value=callResult
	        end
	    end
	    key=tonumber(key) or key
	    t.table[key]=value
	    msp=msp-3
				goto DISPATCH
end
			::TABLE_INDEX::
	do
	    local key=ms[msp-1]
	    key=tonumber(key) or key
	    if key==empty then
	        if arg1==1 then
	            msp=msp-2
	                msp=msp+1
	    ms[msp]=empty
	            goto DISPATCH
	        else
	                return false, "Cannot use empty as key.", ip, chunk
	        end
	    end
	    local _table=ms[msp]
	    local t=_type(_table)
	    if t ~="table" then
	        if arg1==1 then
	            msp=msp-2
	                msp=msp+1
	    ms[msp]=empty
	            goto DISPATCH
	        else
	                return false, "Try to index a '" ..t .."' value.", ip, chunk
	        end
	    end
	    local value=_table.table[key]
	    if not value then
	        if arg1==1 then
	            msp=msp-2
	                msp=msp+1
	    ms[msp]=empty
	            goto DISPATCH
	        elseif _table.meta.table.getindex then
	            local meta=_table.meta.table.getindex
	            local params={key}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            value=callResult
	        else
	            if tonumber(key) then
	                    return false, "Invalid index '" .. key .."'.", ip, chunk
	            else
	                    return false, "Unregistered key '" .. key .."'.", ip, chunk
	            end
	        end
	    end
	    ms[msp-1]=value
	    msp=msp-1
				goto DISPATCH
end
			::TABLE_INDEX_ACC_SELF::
	do
	    table.insert(ms[msf[msfp]], "self")
	    table.insert(ms[msf[msfp]], ms[msp])
	    table.insert(ms[msf[msfp]], false)
	        local key=ms[msp-1]
	    key=tonumber(key) or key
	    if key==empty then
	        if arg1==1 then
	            msp=msp-2
	                msp=msp+1
	    ms[msp]=empty
	            goto DISPATCH
	        else
	                return false, "Cannot use empty as key.", ip, chunk
	        end
	    end
	    local _table=ms[msp]
	    local t=_type(_table)
	    if t ~="table" then
	        if arg1==1 then
	            msp=msp-2
	                msp=msp+1
	    ms[msp]=empty
	            goto DISPATCH
	        else
	                return false, "Try to index a '" ..t .."' value.", ip, chunk
	        end
	    end
	    local value=_table.table[key]
	    if not value then
	        if arg1==1 then
	            msp=msp-2
	                msp=msp+1
	    ms[msp]=empty
	            goto DISPATCH
	        elseif _table.meta.table.getindex then
	            local meta=_table.meta.table.getindex
	            local params={key}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            value=callResult
	        else
	            if tonumber(key) then
	                    return false, "Invalid index '" .. key .."'.", ip, chunk
	            else
	                    return false, "Unregistered key '" .. key .."'.", ip, chunk
	            end
	        end
	    end
	    ms[msp-1]=value
	    msp=msp-1
				goto DISPATCH
end
			::TABLE_SET_META::
	do
	    	    ms[msp-2].meta.table[ms[msp-1]]=ms[msp]
	    msp=msp-3
				goto DISPATCH
end
			::TABLE_INDEX_META::
	do
	    	    ms[msp-1]=ms[msp].meta.table[ms[msp-1]]
	    msp=msp-1
				goto DISPATCH
end
			::TABLE_SET_ACC::
	do
	    table.insert(ms[msf[msfp]], ms[msp])
	    table.insert(ms[msf[msfp]], ms[msp-1])
	    table.insert(ms[msf[msfp]], false)
	    msp=msp-2
				goto DISPATCH
end
			::TABLE_SET_ACC_META::
	do
	    table.insert(ms[msf[msfp]], ms[msp])
	    table.insert(ms[msf[msfp]], ms[msp-1])
	    table.insert(ms[msf[msfp]], true)
	    msp=msp-2
				goto DISPATCH
end
			::TABLE_EXPAND::
	do
	    local t=ms[msp]
	    if _type(t) ~="table" then
	            return false, "Try to expand a '" .._type(t) .."' value.", ip, chunk
	    end
	    msp=msp-1
	    for _, item in ipairs(t.table) do
	        msp=msp+1
	        ms[msp]=item
	    end
	    for _, key in ipairs(t.keys) do
	        table.insert(ms[msf[msfp]], key)
	        table.insert(ms[msf[msfp]], t.table[key])
	        table.insert(ms[msf[msfp]], false)
	    end
				goto DISPATCH
end
			::ENTER_SCOPE::
	do
	    vsfp=vsfp+1
	    vsf[vsfp]=vsp+1-arg1
	    for i=1, arg2-arg1 do
	        vsp=vsp+1
	        vs[vsp]=empty
	    end
				goto DISPATCH
end
			::LEAVE_SCOPE::
	do
	    vsp=vsf[vsfp]-1
	    vsfp=vsfp-1
				goto DISPATCH
end
			::ENTER_FILE::
	do
					goto DISPATCH
end
			::LEAVE_FILE::
	do
					goto DISPATCH
end
			::BEGIN_ACC::
	do
	    msfp=msfp + 1
	    msf[msfp]=msp+1
				goto DISPATCH
end
			::ACC_TABLE::
	do
	    local limit=msf[msfp]+1
	    local keyCount=#ms[limit-1] / 2
	    local args=ptable(msp-limit+1, keyCount)
	    for i=1, msp-limit+1 do
	        args.table[i]=ms[limit+i-1]
	    end
	    for i=1, #ms[limit-1], 3 do
	        if ms[limit-1][i+2] then
	                	local comopps="add mul div sub mod pow"
		local binopps="eq lt gt"
		local unopps="minus"
		local expectedParamCount
		for opp in comopps:gmatch('%S+') do
			if ms[limit-1][i]==opp then
				expectedParamCount=2
			elseif ms[limit-1][i]:match("^" .. opp .. "[rl]$") then
				expectedParamCount=1
			end
		end
		for opp in binopps:gmatch('%S+') do
			if ms[limit-1][i]==opp then
				expectedParamCount=1
			end
		end
		for opp in unopps:gmatch('%S+') do
			if ms[limit-1][i]==opp then
				expectedParamCount=0
			end
		end
		if expectedParamCount then
			if ms[limit-1][i+1].positionalParamCount ~=expectedParamCount then
				    return false, "Wrong number of positionnal parameters for meta-macro '" .. ms[limit-1][i] .. "', " .. ms[limit-1][i+1].positionalParamCount .. " instead of " .. expectedParamCount .. ".", ip, chunk
			end
			if ms[limit-1][i+1].namedParamCount > 1 then
				    return false, "Meta-macro '" .. ms[limit-1][i] .. "' dont support named parameters.", ip, chunk
			end
		elseif ms[limit-1][i] ~="call" and ms[limit-1][i] ~="tostring" and ms[limit-1][i] ~="tonumber" and ms[limit-1][i] ~="getindex" and ms[limit-1][i] ~="setindex" and ms[limit-1][i] ~="next" then
			    return false, "'" .. ms[limit-1][i] .. "' isn't a valid meta-macro name.", ip, chunk
		end
	    args.meta.table[ms[limit-1][i]]=ms[limit-1][i+1]
	        else
	                local key=ms[limit-1][i]
	    local value=ms[limit-1][i+1]
	    key=tonumber(key) or key
	    if not args.table[key] then
	        table.insert(args.keys, ms[limit-1][i])
	    end
	    args.table[key]=value
	        end
	    end
	    ms[limit-1]=args
	    msp=limit - 1
	        msfp=msfp-1
				goto DISPATCH
end
			::ACC_TEXT::
	do
	    local limit=msf[msfp]
	        for i=limit, msp do
	            if ms[i]==empty then
	                ms[i]=""
	            end
	        end
	        ms[limit]=table.concat(ms, "", limit, msp)
	    msp=limit
	        msfp=msfp-1
				goto DISPATCH
end
			::ACC_EMPTY::
	do
	    msp=msp+1
	    ms[msp]=empty
	        msfp=msfp-1
				goto DISPATCH
end
			::ACC_CALL::
	do
	    local macro=ms[msp]
	    msp=msp - 1
	    local t=_type(macro)
	    local self
	    if t=="table" then
	        if macro.meta and macro.meta.table.call then
	            local params=ms[msp]
	            self=macro
	            t="macro"
	            macro=macro.meta.table.call
	        end
	    end
	    if t=="macro" then
	        local capture
	        local parameters={}
	        if macro.variadicOffset>0 then
	            capture=ptable(0, 0)
	        end
	            local argcount=msp-msf[msfp]
	    if argcount ~=macro.positionalParamCount and macro.variadicOffset==0 then
	        local name
	        if chunk.mapping[ip-1] then
	            name=chunk.mapping[ip-1].content
	        end
	        if not name then
	            name=macro.name or "???"
	        end
	            return false, "Wrong number of positionnal arguments for macro '" .. name .. "', " ..   argcount .. " instead of " .. macro.positionalParamCount .. ".", ip, chunk
	    end
	    for i=1, macro.positionalParamCount do
	        parameters[i]=ms[msp+i-argcount]
	    end
	    for i=macro.positionalParamCount+1, argcount do
	        table.insert(capture.table, ms[msp+i-argcount])
	    end
	    msp=msf[msfp]
	            for i=1, #ms[msf[msfp]], 3 do
	        local k=ms[msf[msfp]][i]
	        local v=ms[msf[msfp]][i+1]
	        local m=ms[msf[msfp]][i+2]
	        local j=macro.namedParamOffset[k]
	        if m then
	                	local comopps="add mul div sub mod pow"
		local binopps="eq lt gt"
		local unopps="minus"
		local expectedParamCount
		for opp in comopps:gmatch('%S+') do
			if k==opp then
				expectedParamCount=2
			elseif k:match("^" .. opp .. "[rl]$") then
				expectedParamCount=1
			end
		end
		for opp in binopps:gmatch('%S+') do
			if k==opp then
				expectedParamCount=1
			end
		end
		for opp in unopps:gmatch('%S+') do
			if k==opp then
				expectedParamCount=0
			end
		end
		if expectedParamCount then
			if v.positionalParamCount ~=expectedParamCount then
				    return false, "Wrong number of positionnal parameters for meta-macro '" .. k .. "', " .. v.positionalParamCount .. " instead of " .. expectedParamCount .. ".", ip, chunk
			end
			if v.namedParamCount > 1 then
				    return false, "Meta-macro '" .. k .. "' dont support named parameters.", ip, chunk
			end
		elseif k ~="call" and k ~="tostring" and k ~="tonumber" and k ~="getindex" and k ~="setindex" and k ~="next" then
			    return false, "'" .. k .. "' isn't a valid meta-macro name.", ip, chunk
		end
	    capture.meta.table[k]=v
	        elseif j then
	            parameters[j]=v
	        elseif macro.variadicOffset>0 then
	                local key=k
	    local value=v
	    key=tonumber(key) or key
	    if not capture.table[key] then
	        table.insert(capture.keys, k)
	    end
	    capture.table[key]=value
	        else
	            local name=macro.name or "???"
	                return false, "Unknow named parameter '" .. k .."' for macro '" .. name .."'.", ip, chunk
	        end
	    end
	    msp=msp-1
	        if self then
	            table.insert(parameters, self)
	        end
	        if macro.variadicOffset>0 then
	            parameters[macro.variadicOffset]=capture
	        end
	            msfp=msfp-1
	            table.insert(chunk.callstack, {chunk=chunk, macro=macro, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(macro, parameters)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	        msp=msp+1
	        ms[msp]=callResult
	    elseif t=="luaFunction" then
	            local limit=msf[msfp]+1
	    local keyCount=#ms[limit-1] / 2
	    local args=ptable(msp-limit+1, keyCount)
	    for i=1, msp-limit+1 do
	        args.table[i]=ms[limit+i-1]
	    end
	    for i=1, #ms[limit-1], 3 do
	        if ms[limit-1][i+2] then
	                	local comopps="add mul div sub mod pow"
		local binopps="eq lt gt"
		local unopps="minus"
		local expectedParamCount
		for opp in comopps:gmatch('%S+') do
			if ms[limit-1][i]==opp then
				expectedParamCount=2
			elseif ms[limit-1][i]:match("^" .. opp .. "[rl]$") then
				expectedParamCount=1
			end
		end
		for opp in binopps:gmatch('%S+') do
			if ms[limit-1][i]==opp then
				expectedParamCount=1
			end
		end
		for opp in unopps:gmatch('%S+') do
			if ms[limit-1][i]==opp then
				expectedParamCount=0
			end
		end
		if expectedParamCount then
			if ms[limit-1][i+1].positionalParamCount ~=expectedParamCount then
				    return false, "Wrong number of positionnal parameters for meta-macro '" .. ms[limit-1][i] .. "', " .. ms[limit-1][i+1].positionalParamCount .. " instead of " .. expectedParamCount .. ".", ip, chunk
			end
			if ms[limit-1][i+1].namedParamCount > 1 then
				    return false, "Meta-macro '" .. ms[limit-1][i] .. "' dont support named parameters.", ip, chunk
			end
		elseif ms[limit-1][i] ~="call" and ms[limit-1][i] ~="tostring" and ms[limit-1][i] ~="tonumber" and ms[limit-1][i] ~="getindex" and ms[limit-1][i] ~="setindex" and ms[limit-1][i] ~="next" then
			    return false, "'" .. ms[limit-1][i] .. "' isn't a valid meta-macro name.", ip, chunk
		end
	    args.meta.table[ms[limit-1][i]]=ms[limit-1][i+1]
	        else
	                local key=ms[limit-1][i]
	    local value=ms[limit-1][i+1]
	    key=tonumber(key) or key
	    if not args.table[key] then
	        table.insert(args.keys, ms[limit-1][i])
	    end
	    args.table[key]=value
	        end
	    end
	    ms[limit-1]=args
	    msp=limit - 1
	        msfp=msfp-1
	        table.insert(chunk.callstack, {chunk=chunk, macro=macro, ip=ip})
	        local success, result=pcall(macro.callable, ms[msp], chunk)
	        if not success then
	            return success, result, ip, chunk
	        end
	        table.remove(chunk.callstack)
	        if result==nil then
	            result=empty
	        end
	        ms[msp]=result
	    else
	            return false, "Try to call a '" .. t .. "' value", ip, chunk
	    end
				goto DISPATCH
end
			::RETURN::
	do
	    jump=calls[cp]
	    if not jump then
	        jump=#bytecode
	    end
	    cp=cp - 1
	        vsp=vsf[vsfp]-1
	    vsfp=vsfp-1
				goto DISPATCH
end
			::ACC_CHECK_TEXT::
	do
	    local t=_type(ms[msp])
	    if t ~="number" and t ~="string" and ms[msp] ~=empty then
	        if t=="table" and ms[msp].meta.table.tostring then
	            local meta=ms[msp].meta.table.tostring
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            ms[msp]=callResult
	        else
	                return false, "Cannot concat a '" ..t .. "' value.", ip, chunk
	        end
	    end
				goto DISPATCH
end
			::JUMP_IF::
	do
	    local test=ms[msp]
	        if test==empty then
	        test=false
	    end
	    if test then
	        jump=arg2
	    end
	    msp=msp-1
				goto DISPATCH
end
			::JUMP_IF_NOT::
	do
	    local test=ms[msp]
	        if test==empty then
	        test=false
	    end
	    if not test then
	        jump=arg2
	    end
	    msp=msp-1
				goto DISPATCH
end
			::JUMP_IF_NOT_EMPTY::
	do
	    if ms[msp] ~=empty then
	        jump=arg2
	    end
	    msp=msp-1
				goto DISPATCH
end
			::JUMP::
	do
	    jump=arg2
				goto DISPATCH
end
			::JUMP_IF_PEEK::
	do
	    local test=ms[msp]
	        if test==empty then
	        test=false
	    end
	    if test then
	        jump=arg2
	    end
				goto DISPATCH
end
			::JUMP_IF_NOT_PEEK::
	do
	    local test=ms[msp]
	        if test==empty then
	        test=false
	    end
	    if not test then
	        jump=arg2
	    end
				goto DISPATCH
end
			::GET_ITER::
	do
	    local obj=ms[msp]
	    local tobj=_type(obj)
	    if tobj ~="table" then
	            return false, "Try to iterate over a non-table '" .. tobj .. "' value.", ip, chunk
	    end
	    local iter
	    if obj.meta.table.next then
	        iter=obj
	    else
	        iter=obj.meta.table.iter
	    end
	    if iter.type=="luaFunction" then
	        ms[msp]=iter.callable()
	    elseif iter.type=="table" then
	        ms[msp]=iter
	    end
				goto DISPATCH
end
			::FOR_ITER::
	do
	    local obj=ms[msp]
	    local iter=obj.meta.table.next
	    local result
	    if iter.type=="luaFunction" then
	        result=iter.callable()
	    else
	            table.insert(chunk.callstack, {chunk=chunk, macro=iter, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(iter, {obj})
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	        result=callResult
	    end
	    if result==empty then
	        msp=msp-1
	            jump=arg2
	    else
	        ms[msp]=result
	    end
				goto DISPATCH
end
			::OPP_ADD::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	    local err
	        if _type(x)=="string" then
	        x=tonumber(x)
	        if not x then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(x) ~="number" then
	        if _type(x)=="table" and x.meta.table.tonumber then
	            local meta=x.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            x=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(x).. " value."
	        end
	    end
	        if _type(y)=="string" then
	        y=tonumber(y)
	        if not y then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(y) ~="number" then
	        if _type(y)=="table" and y.meta.table.tonumber then
	            local meta=y.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            y=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(y).. " value."
	        end
	    end
	    msp=msp-1
	    if err then
	            local meta
	    local params
	    if _type(x)=="table" and x.meta and x.meta.table.addr then
	        meta=x.meta.table.addr
	        params={y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.addl then
	        meta=y.meta.table.addl
	        params={x, y}
	    elseif _type(x)=="table" and x.meta and x.meta.table.add then
	        meta=x.meta.table.add
	        params={x, y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.add then
	        meta=y.meta.table.add
	        params={x, y, y}
	    end
	    if not meta then
	            return false, err, ip, chunk
	    end
	        table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	    ms[msp]=callResult
	    else
	        ms[msp]=x + y
	    end
				goto DISPATCH
end
			::OPP_MUL::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	    local err
	        if _type(x)=="string" then
	        x=tonumber(x)
	        if not x then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(x) ~="number" then
	        if _type(x)=="table" and x.meta.table.tonumber then
	            local meta=x.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            x=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(x).. " value."
	        end
	    end
	        if _type(y)=="string" then
	        y=tonumber(y)
	        if not y then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(y) ~="number" then
	        if _type(y)=="table" and y.meta.table.tonumber then
	            local meta=y.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            y=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(y).. " value."
	        end
	    end
	    msp=msp-1
	    if err then
	            local meta
	    local params
	    if _type(x)=="table" and x.meta and x.meta.table.mulr then
	        meta=x.meta.table.mulr
	        params={y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.mull then
	        meta=y.meta.table.mull
	        params={x, y}
	    elseif _type(x)=="table" and x.meta and x.meta.table.mul then
	        meta=x.meta.table.mul
	        params={x, y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.mul then
	        meta=y.meta.table.mul
	        params={x, y, y}
	    end
	    if not meta then
	            return false, err, ip, chunk
	    end
	        table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	    ms[msp]=callResult
	    else
	        ms[msp]=x * y
	    end
				goto DISPATCH
end
			::OPP_SUB::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	    local err
	        if _type(x)=="string" then
	        x=tonumber(x)
	        if not x then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(x) ~="number" then
	        if _type(x)=="table" and x.meta.table.tonumber then
	            local meta=x.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            x=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(x).. " value."
	        end
	    end
	        if _type(y)=="string" then
	        y=tonumber(y)
	        if not y then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(y) ~="number" then
	        if _type(y)=="table" and y.meta.table.tonumber then
	            local meta=y.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            y=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(y).. " value."
	        end
	    end
	    msp=msp-1
	    if err then
	            local meta
	    local params
	    if _type(x)=="table" and x.meta and x.meta.table.subr then
	        meta=x.meta.table.subr
	        params={y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.subl then
	        meta=y.meta.table.subl
	        params={x, y}
	    elseif _type(x)=="table" and x.meta and x.meta.table.sub then
	        meta=x.meta.table.sub
	        params={x, y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.sub then
	        meta=y.meta.table.sub
	        params={x, y, y}
	    end
	    if not meta then
	            return false, err, ip, chunk
	    end
	        table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	    ms[msp]=callResult
	    else
	        ms[msp]=x - y
	    end
				goto DISPATCH
end
			::OPP_DIV::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	    local err
	        if _type(x)=="string" then
	        x=tonumber(x)
	        if not x then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(x) ~="number" then
	        if _type(x)=="table" and x.meta.table.tonumber then
	            local meta=x.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            x=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(x).. " value."
	        end
	    end
	        if _type(y)=="string" then
	        y=tonumber(y)
	        if not y then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(y) ~="number" then
	        if _type(y)=="table" and y.meta.table.tonumber then
	            local meta=y.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            y=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(y).. " value."
	        end
	    end
	    msp=msp-1
	    if err then
	            local meta
	    local params
	    if _type(x)=="table" and x.meta and x.meta.table.divr then
	        meta=x.meta.table.divr
	        params={y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.divl then
	        meta=y.meta.table.divl
	        params={x, y}
	    elseif _type(x)=="table" and x.meta and x.meta.table.div then
	        meta=x.meta.table.div
	        params={x, y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.div then
	        meta=y.meta.table.div
	        params={x, y, y}
	    end
	    if not meta then
	            return false, err, ip, chunk
	    end
	        table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	    ms[msp]=callResult
	    else
	        ms[msp]=x / y
	    end
				goto DISPATCH
end
			::OPP_NEG::
	do
	    x=ms[msp]
	    local err
	        if _type(x)=="string" then
	        x=tonumber(x)
	        if not x then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(x) ~="number" then
	        if _type(x)=="table" and x.meta.table.tonumber then
	            local meta=x.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            x=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(x).. " value."
	        end
	    end
	    if err then
	            local meta
	    local params={x}
	    if _type(x)=="table" and x.meta and x.meta.table.minus then
	        meta=x.meta.table.minus
	    end
	    if not meta then
	            return false, err, ip, chunk
	    end
	        table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	    ms[msp]=callResult
	    else
	        ms[msp]=- x
	    end
				goto DISPATCH
end
			::OPP_MOD::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	    local err
	        if _type(x)=="string" then
	        x=tonumber(x)
	        if not x then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(x) ~="number" then
	        if _type(x)=="table" and x.meta.table.tonumber then
	            local meta=x.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            x=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(x).. " value."
	        end
	    end
	        if _type(y)=="string" then
	        y=tonumber(y)
	        if not y then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(y) ~="number" then
	        if _type(y)=="table" and y.meta.table.tonumber then
	            local meta=y.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            y=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(y).. " value."
	        end
	    end
	    msp=msp-1
	    if err then
	            local meta
	    local params
	    if _type(x)=="table" and x.meta and x.meta.table.modr then
	        meta=x.meta.table.modr
	        params={y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.modl then
	        meta=y.meta.table.modl
	        params={x, y}
	    elseif _type(x)=="table" and x.meta and x.meta.table.mod then
	        meta=x.meta.table.mod
	        params={x, y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.mod then
	        meta=y.meta.table.mod
	        params={x, y, y}
	    end
	    if not meta then
	            return false, err, ip, chunk
	    end
	        table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	    ms[msp]=callResult
	    else
	        ms[msp]=x % y
	    end
				goto DISPATCH
end
			::OPP_POW::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	    local err
	        if _type(x)=="string" then
	        x=tonumber(x)
	        if not x then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(x) ~="number" then
	        if _type(x)=="table" and x.meta.table.tonumber then
	            local meta=x.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            x=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(x).. " value."
	        end
	    end
	        if _type(y)=="string" then
	        y=tonumber(y)
	        if not y then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(y) ~="number" then
	        if _type(y)=="table" and y.meta.table.tonumber then
	            local meta=y.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            y=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(y).. " value."
	        end
	    end
	    msp=msp-1
	    if err then
	            local meta
	    local params
	    if _type(x)=="table" and x.meta and x.meta.table.powr then
	        meta=x.meta.table.powr
	        params={y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.powl then
	        meta=y.meta.table.powl
	        params={x, y}
	    elseif _type(x)=="table" and x.meta and x.meta.table.pow then
	        meta=x.meta.table.pow
	        params={x, y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.pow then
	        meta=y.meta.table.pow
	        params={x, y, y}
	    end
	    if not meta then
	            return false, err, ip, chunk
	    end
	        table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	    ms[msp]=callResult
	    else
	        ms[msp]=x ^ y
	    end
				goto DISPATCH
end
			::OPP_GTE::
	do
					goto DISPATCH
end
			::OPP_LTE::
	do
					goto DISPATCH
end
			::OPP_GT::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	    local err
	        if _type(x)=="string" then
	        x=tonumber(x)
	        if not x then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(x) ~="number" then
	        if _type(x)=="table" and x.meta.table.tonumber then
	            local meta=x.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            x=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(x).. " value."
	        end
	    end
	        if _type(y)=="string" then
	        y=tonumber(y)
	        if not y then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(y) ~="number" then
	        if _type(y)=="table" and y.meta.table.tonumber then
	            local meta=y.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            y=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(y).. " value."
	        end
	    end
	    msp=msp-1
	    if err then
	        local macro, params, meta
	        if _type(x)=="table" and x.meta and x.meta.table.gt then
	            meta=x.meta.table.gt
	            params={y, x}
	        elseif _type(y)=="table" and y.meta and y.meta.table.lt then
	            meta=y.meta.table.lt
	            params={x, y}
	        end
	        if not meta then
	                return false, err, ip, chunk
	        end
	            table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	        if invert then
	            callResult=not callResult
	            if callResult then
	                ms[msp]=callResult
	            else
	                msp=msp+1
	                    x=ms[msp-1]
	    y=ms[msp]
	    msp=msp-1
	    local macro, params, meta
	    if _type(x)=="table" and x.meta and x.meta.table.eq then
	        meta=x.meta.table.eq
	        params={y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.eq then
	        meta=y.meta.table.eq
	        params={x, y}
	    end
	    if meta then
	            table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	        ms[msp]=callResult
	    else
	            if _type(x)=="string" then
	        x=tonumber(x) or x
	    end
	            if _type(y)=="string" then
	        y=tonumber(y) or y
	    end
	        ms[msp]=x==y
	    end
	            end
	        else
	            ms[msp]=callResult
	        end
	    else
	        ms[msp]=x > y
	    end
				goto DISPATCH
end
			::OPP_LT::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	    local err
	        if _type(x)=="string" then
	        x=tonumber(x)
	        if not x then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(x) ~="number" then
	        if _type(x)=="table" and x.meta.table.tonumber then
	            local meta=x.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            x=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(x).. " value."
	        end
	    end
	        if _type(y)=="string" then
	        y=tonumber(y)
	        if not y then
	            err="Cannot convert the string value to a number."
	        end
	    elseif _type(y) ~="number" then
	        if _type(y)=="table" and y.meta.table.tonumber then
	            local meta=y.meta.table.tonumber
	            local params={}
	                table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	            y=callResult
	        else
	            err="Cannot do comparison or arithmetic with " .. _type(y).. " value."
	        end
	    end
	    msp=msp-1
	    if err then
	        local macro, params, meta, invert
	        if _type(x)=="table" and x.meta and x.meta.table.lt then
	            meta=x.meta.table.lt
	            params={y, x}
	        elseif _type(y)=="table" and y.meta and y.meta.table.gt then
	            meta=y.meta.table.gt
	            params={x, y}
	        elseif _type(x)=="table" and x.meta and x.meta.table.gt then
	            meta=x.meta.table.gt
	            params={y, x}
	            invert=true
	        elseif _type(y)=="table" and y.meta and y.meta.table.lt then
	            meta=y.meta.table.lt
	            params={x, y}
	            invert=true
	        end
	        if not meta then
	                return false, err, ip, chunk
	        end
	            table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	        if invert then
	            callResult=not callResult
	            if callResult then
	                ms[msp]=callResult
	            else
	                msp=msp+1
	                    x=ms[msp-1]
	    y=ms[msp]
	    msp=msp-1
	    local macro, params, meta
	    if _type(x)=="table" and x.meta and x.meta.table.eq then
	        meta=x.meta.table.eq
	        params={y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.eq then
	        meta=y.meta.table.eq
	        params={x, y}
	    end
	    if meta then
	            table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	        ms[msp]=callResult
	    else
	            if _type(x)=="string" then
	        x=tonumber(x) or x
	    end
	            if _type(y)=="string" then
	        y=tonumber(y) or y
	    end
	        ms[msp]=x==y
	    end
	            end
	        else
	            ms[msp]=callResult
	        end
	    else
	        ms[msp]=x < y
	    end
				goto DISPATCH
end
			::OPP_EQ::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	    msp=msp-1
	    local macro, params, meta
	    if _type(x)=="table" and x.meta and x.meta.table.eq then
	        meta=x.meta.table.eq
	        params={y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.eq then
	        meta=y.meta.table.eq
	        params={x, y}
	    end
	    if meta then
	            table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	        ms[msp]=callResult
	    else
	            if _type(x)=="string" then
	        x=tonumber(x) or x
	    end
	            if _type(y)=="string" then
	        y=tonumber(y) or y
	    end
	        ms[msp]=x==y
	    end
				goto DISPATCH
end
			::OPP_NEQ::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	    msp=msp-1
	    local macro, params, meta
	    if _type(x)=="table" and x.meta and x.meta.table.eq then
	        meta=x.meta.table.eq
	        params={y, x}
	    elseif _type(y)=="table" and y.meta and y.meta.table.eq then
	        meta=y.meta.table.eq
	        params={x, y}
	    end
	    if meta then
	            table.insert(chunk.callstack, {chunk=chunk, macro=meta, ip=ip})
	    if #chunk.callstack>1000 then
	            return false, "stack overflow", ip, chunk
	    end
	    local success, callResult, cip, source=plume.run(meta, params)
	    if not success then
	        return success, callResult, cip, (source or macro)
	    end
	    table.remove(chunk.callstack)
	        ms[msp]=not callResult
	    else
	            if _type(x)=="string" then
	        x=tonumber(x) or x
	    end
	            if _type(y)=="string" then
	        y=tonumber(y) or y
	    end
	        ms[msp]=x ~=y
	    end
				goto DISPATCH
end
			::OPP_AND::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	        if x==empty then
	        x=false
	    end
	        if y==empty then
	        y=false
	    end
	    msp=msp-1
	    ms[msp]=x and y
				goto DISPATCH
end
			::OPP_NOT::
	do
	    x=ms[msp]
	        if x==empty then
	        x=false
	    end
	    ms[msp]=not x
				goto DISPATCH
end
			::OPP_OR::
	do
	    x=ms[msp-1]
	    y=ms[msp]
	        if x==empty then
	        x=false
	    end
	        if y==empty then
	        y=false
	    end
	    msp=msp-1
	    ms[msp]=x or y
				goto DISPATCH
end
			::DUPLICATE::
	do
	    msp=msp+1
	    ms[msp]=ms[msp-1]
				goto DISPATCH
end
			::SWITCH::
	do
	    local temp=ms[msp]
	    ms[msp]=ms[msp-1]
	    ms[msp-1]=temp
				goto DISPATCH
end
		::END::
        	local result=empty
        if #ms >=1 then
            result=ms[1]
        end
        return true, result, ip
    end
end
