--File generated by preprocessor.lua
--[[This file is part of Plume
Plume🪶 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.
Plume🪶 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with Plume🪶.
If not, see <https://www.gnu.org/licenses/>.
]]

return function(plume)
	local function throwCompilationError(node, message)
		message = plume.error.makeCompilationError(node, message)
		error(message, -1)
	end

	local function throwSyntaxError(node, message)
		message = plume.error.makeSyntaxError(node, message)
		error(message, -1)
	end

	function plume.error.useUnknowVariableError(node, varName)
		local message = string.format("Cannot use variable '%s', it isn't defined in the current scope.", varName)
		throwCompilationError(node, message)
	end

	function plume.error.setUnknowVariableError(node, varName)
		local message = string.format("Cannot set variable '%s', it isn't defined in the current scope.", varName)
		throwCompilationError(node, message)
	end

	function plume.error.setConstantVariableError(node, varName)
		local message = string.format("Cannot set variable '%s', it is a constant.", varName)
		throwCompilationError(node, message)
	end

	function plume.error.letEmptyConstantError(node)
		local message = string.format("Cannot define an empty constant variable.", varName)
		throwCompilationError(node, message)
	end

	function plume.error.letExistingVariableError(node, varName)
		local message = string.format("Cannot define variable '%s', it already exists in the current scope.", varName)
		throwCompilationError(node, message)
	end

	function plume.error.letExistingStaticVariableError(node, varName)
		local message = string.format("Cannot define static variable '%s', it already exists in the current file scope.", varName)
		throwCompilationError(node, message)
	end

	function plume.error.cannotSetCallError(node)
		local message = "Cannot set the result of a call."
		throwCompilationError(node, message)
	end

	function plume.error.cannotUseBreakOutsideLoop(node)
		local message = "Cannot use break keyword outside a loop."
		throwCompilationError(node, message)
	end

	function plume.error.cannotUseContinueOutsideLoop(node)
		local message = "Cannot use continue keyword outside a loop."
		throwCompilationError(node, message)
	end

	function plume.error.missingIteratorError(node)
		local message = "Missing iterator."
		throwSyntaxError(node, message)
	end

	function plume.error.missingConditionError(node)
		local message = "Missing condition."
		throwSyntaxError(node, message)
	end

	function plume.error.missingEndError(node)
		local message = "Missing end."
		throwSyntaxError(node, message)
	end

	function plume.error.emptyExprError(node)
		local message = "Evaluation cannot be empty."
		throwSyntaxError(node, message)
	end

	function plume.error.missingClosingBraveError(node)
		local message = "Missing ')' to close evaluation."
		throwSyntaxError(node, message)
	end

	function plume.error.missingLoopIdentifierError(node)
		local message = "Missing loop identifier."
		throwSyntaxError(node, message)
	end

	function plume.error.missingParamListError(node)
		local message = "Missing parameters list."
		throwSyntaxError(node, message)
	end

	function plume.error.missingParamError(node)
		local message = "Missing parameter name."
		throwSyntaxError(node, message)
	end

	function plume.error.emptySetError(node)
		local message = "Using set without giving it a value."
		throwSyntaxError(node, message)
	end


	function plume.error.malformedCodeError(node)
		local message = "Malformed code."
		throwSyntaxError(node, message)
	end

	function plume.error.mixedBlockError(node, expected, found)
		local message = string.format("Mixed block: the expected type of the block is %s, but it contains an element %s.", expected, found)
		throwSyntaxError(node, message)
	end
end