--[[This file is part of Plume

Plume🪶 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.

Plume🪶 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Plume🪶.
If not, see <https://www.gnu.org/licenses/>.
]]

-- Optimize engine.lua to performances
-- Thanks for thenumbernine lua-parser lib.

package.path =  "build-tools/?.lua;build-tools/thenumbernine/?.lua;build-tools/thenumbernine/ext/?.lua;;build-tools/thenumbernine/parser/?.lua;;build-tools/thenumbernine/template/?.lua;" .. package.path

local ast = require "parser.lua.ast"
local tolua = require 'ext.tolua'
local optimizer = require"luaOptimizer"
local cleaner = require"luaCleaner"
local beautifier = require "luaBeautifier"

local function printTable(t)
	print(tolua(t))
end

local debug = false

require "make-engine" -- Compile base file
local tree

if debug then
	tree = optimizer.loadCode([[
do
    mainStackPointer = mainStackPointer + 1
    mainStack[mainStackPointer] = constants[arg2]
end
]], false)
else
	tree = optimizer.loadCode('plume-data/engine/engine.lua', true)
end

-- printTable(tree)

tree:traverse(optimizer.inlineRequire)
tree:traverse(optimizer.renameRun)
tree:traverse(optimizer.saveFunctionsToInline)
tree:traverse(optimizer.inlineFunctions)
tree:traverse(optimizer.applyInsertBefore)
tree:traverse(optimizer.applyInsertExprs)
tree:traverse(optimizer.inlineIndex)
tree:traverse(optimizer.inlineIndex)
tree:traverse(optimizer.inlineIndex)
tree:traverse(optimizer.tolocal)

tree = optimizer.loadCode(beautifier(tree), false)
tree:traverse(cleaner.removeUselessDo)


local finalCode = beautifier(tree)
if debug then
	print(finalCode)
else
	finalCode = [=[--[[This file is part of Plume

Plume🪶 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.

Plume🪶 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Plume🪶.
If not, see <https://www.gnu.org/licenses/>.
]]

-- Generated by make-engine-opt.lua
-- It is an inlined and optimized version of engine.lua
]=] .. finalCode


	local f = io.open('plume-data/engine/engine-opt.lua', 'w')
		f:write(finalCode)
	f:close()
end

