--[[This file is part of Plume

Plume🪶 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.

Plume🪶 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Plume🪶.
If not, see <https://www.gnu.org/licenses/>.
]]

-- This module takes an AST generated by `makeAST.lua` and converts it to
-- executable Lua code. It uses a builder to construct Lua code and maintain
-- a source map for debugging purposes.
-- The transpilation process involves recursively traversing the AST and
-- dispatching to specific handler functions based on node type.

--- Configures the Plume to Lua transpilation capabilities.
-- This function initializes the transpiler, sets up helper functions,
-- and adds the `transpileToLua` method to the provided Plume instance.
return function(plume)

    local contains = plume.utils.containsWord

    -- Initialize the Lua code builder instance.
    local transpiler = require "engine/transpiler/lua/builder" (plume)
    
    require "engine/transpiler/lua/transpileChildren" (plume, transpiler)
    require "engine/transpiler/lua/tokenHandlers"     (plume, transpiler)
    require "engine/transpiler/lua/header"            (plume, transpiler)
    
    --- Post-processes generated Lua code to transform Plume-style function and method calls.
    -- This function converts:
    -- 1. Standard function calls `func(arg1, arg2)` into `func{arg1, arg2}`.
    -- 2. Plume-style method calls `object:method(arg1, arg2)` into `object.method{self=object, arg1, arg2}`.
    --
    -- This transformation implies that the Lua code initially generated by the transpiler
    -- expects functions to be called with a single table argument encapsulating all actual arguments,
    -- and optionally a `self` field for method calls.
    --
    -- NOTE: This is a temporary, regex-based hack used to handle Plume's object model
    -- and function call conventions before full parser integration. It is not a general Lua parser.
    ---@param code string The Lua code string to process.
    ---@return string The modified Lua code string.
    function transpiler.editLuaCode(code)
        code = code:gsub('([a-zA-Z_][a-zA-Z_0-9%.%:]*)%s*(%b())', function(name, params)
            params = params:sub(2, -2) -- Remove parentheses from parameter string
            -- Replace colons with dots (e.g., obj:method -> obj.method) to unify method access.
            -- This is part of the hack and assumes ':' is used exclusively for method calls in this context.
            name = name:gsub(':', '.')
            local tableName, methodName = name:match("^(.-)%.([^%.]+)$")

            if tableName then
                -- It's a method call like object.method after colon replacement
                return name .. "{self=" .. tableName .. ", " .. params .. "}"
            else
                -- It's a simple function call
                return name .. "{" .. params .. "}"
            end
        end)

        return code
    end
   
    --- Transpiles a single AST node by dispatching to a registered handler.
    ---@param ast table The AST node to transpile.
    function transpiler.transpileToLua(ast)
        if transpiler.tokenHandlers[ast.kind] then
            transpiler.tokenHandlers[ast.kind](ast)
        else
            error("NIY: Transpilation for AST node kind '" .. (ast.kind or "???") .. "' is not implemented yet.")
        end
    end

    --- Converts an entire AST into a Lua code string and its corresponding source map.
    ---@param ast table The Abstract Syntax Tree to transpile.
    ---@return string transpiledCode The concatenated Lua source code.
    ---@return table sourceMap The mapping information for the transpiled code.
    plume.transpileToLua = function(ast, filename)
        local map = {{}} -- Initialize the source map.

        local dir = filename:gsub('[^\\/]+$', '')
        dir = dir:gsub('[\\/]$', '')
        if #dir == 0 then
            dir = "."
        end
        -- Initialize the transpiler builder with the source map.
        transpiler:init (map)

        -- Special variables
        transpiler:insert("local _FILE = \"" .. filename .. "\"")
        transpiler:newline()
        transpiler:insert("local _DIR  = \"" .. dir .. "\"")
        transpiler:newline()

        -- Start the recursive transpilation process from the root AST node.
        transpiler.transpileToLua(ast)

        -- Add declarations
        transpiler:genHeader()
        
        -- Return the concatenated Lua code and the source map.
        return table.concat(transpiler.code), map
    end
end