--[[This file is part of Plume

Plume🪶 is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, version 3 of the License.

Plume🪶 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with Plume🪶.
If not, see <https://www.gnu.org/licenses/>.
]]

return function(plume)
    local contains = plume.utils.containsWord
    
    --- Post-processes generated Lua code to transform Plume-style function and method calls.
    -- This function converts:
    -- 1. Standard function calls `func(arg1, arg2)` into `func{arg1, arg2}`.
    -- 2. Plume-style method calls `object:method(arg1, arg2)` into `object.method{self=object, arg1, arg2}`.
    --
    -- This transformation implies that the Lua code initially generated by the transpiler
    -- expects functions to be called with a single table argument encapsulating all actual arguments,
    -- and optionally a `self` field for method calls.
    --
    -- NOTE: This is a temporary, regex-based hack used to handle Plume's object model
    -- and function call conventions before full parser integration. It is not a general Lua parser.
    ---@param code string The Lua code string to process.
    ---@return string The modified Lua code string.
    function plume.editLuaCode(code)
        code = code:gsub('([a-zA-Z_][a-zA-Z_0-9%.%:]*)%s*(%b())', function(name, params)
            params = params:sub(2, -2) -- Remove parentheses from parameter string
            -- Replace colons with dots (e.g., obj:method -> obj.method) to unify method access.
            -- This is part of the hack and assumes ':' is used exclusively for method calls in this context.
            name = name:gsub(':', '.')
            local tableName, methodName = name:match("^(.-)%.([^%.]+)$")

            if tableName then
                -- It's a method call like object.method after colon replacement
                return name .. "{self=" .. tableName .. ", " .. params .. "}"
            else
                -- It's a simple function call
                return name .. "{" .. params .. "}"
            end
        end)
        
        if code == "" then
            code = '""'
        end
        
        return code
    end

    function plume.escapeLuaString(s)
        s = s:gsub('"', '\\"')
        return s
    end
    
    function plume.shortNodeInfos(children, canPutParens)
        if #children == 0 then
            return '""'
        elseif #children == 1 then
            local child = children[1]
            if child.kind == "TEXT" then
                if child.content:match('^[0-9]+$') or child.content:match('^[0-9]+%.[0-9]+$') then
                    return child.content
                else
                    return '"'..plume.escapeLuaString(child.content)..'"'
                end
            elseif child.kind == "LUA_EXPRESSION" then
                local code = plume.editLuaCode(child.content)
                if canPutParens then
                    -- Parenthesis make easier to restrain lua error to the correct line
                    code = "(" .. code .. ")"
                end
                return code
            elseif child.kind == "VARIABLE" then
                return child.content
            end
        end
    end
    
    function plume.getLuaVariableName(node)
        local name = node.content
        for _, index in ipairs(node.sourceToken.index or {}) do
            if index.kind == "INDEX_ACCESS" then
                name = name
                    .. "["
                        .. plume.editLuaCode(index.content)
                    .. "]"
            elseif index.kind == "FIELD_ACCESS" then
                name = name .. "." .. index.content
            end
        end
        return name
    end
    
    local function readMacroDefinitionParameters(parameters)
        local positionalArgs = {}
        local namedArgs      = {}
        local validators     = {}
        local varargPos, varargNamed

        for i, child in ipairs(parameters.children) do
            if child.kind == "LIST_ITEM" then -- Positional parameter.
                local name      = child.children[1].name
                local validator = child.children[1].validator
                
                local validatorVararg
                

                if name == "self" then
                    plume.cannotUseSelfError(child.children[1].sourceToken.source)
                end

                if child.children[1].kind == "VARARG_POSITIONAL" then
                    varargPos = name
                    validatorVararg = 1
                elseif child.children[1].kind == "VARARG_NAMED" then
                    varargNamed = name
                    validatorVararg = 2
                else
                    table.insert(positionalArgs, name)
                end
                
                if validator then
                    table.insert(validators, {name, validator, '#' .. i, validatorVararg})
                end
            elseif child.kind == "HASH_ITEM" then -- named parameter
                local name      = child.children[1].name
                local validator = child.children[1].validator

                if validator then
                    table.insert(validators, {name, validator, name})
                end

                child.name = name

                table.insert(namedArgs, child)
            end
        end
        
        return positionalArgs, namedArgs, validators, varargPos, varargNamed
    end
    
    local function makeMacroInit(macroName, positionalArgs, namedArgs, validators, varargPos, varargNamed, meta)
        local stringPositionalArgs = table.concat(positionalArgs, ", ")
        
        local stringNamedArgs = {}
        for _, node in ipairs(namedArgs) do
            table.insert(stringNamedArgs, node.name)
        end
        stringNamedArgs = table.concat(stringNamedArgs, ", ")

        local stringVarargCheckPos, stringVarargCheckNamed
        if varargPos then
            stringVarargCheckPos = "true"
        else
            stringVarargCheckPos = "false"
        end
        if varargNamed then
            stringVarargCheckNamed = "true"
        else
            stringVarargCheckNamed = "false"
        end
        
        local result = {}
        table.insert(result, "local self")

        if #stringPositionalArgs > 0 then
            table.insert(result, ", ")
            table.insert(result, stringPositionalArgs)
        end
        if #namedArgs > 0 then
            table.insert(result, ", ")
            table.insert(result, stringNamedArgs)
        end
        if varargPos then
            table.insert(result, ", ")
            table.insert(result, varargPos)
        end
        if varargNamed then
            table.insert(result, ", ")
            table.insert(result, varargNamed)
        end

        table.insert(result, " = ")

        table.insert(result, "__plume_initArgs(")
            table.insert(result, "__plume_args, ")
            table.insert(result, #positionalArgs)
            table.insert(result, ", ")
            table.insert(result, "{") -- Start of named arguments table.
            --- Insert named argument information into the table.
            for i, node in ipairs(namedArgs) do
                table.insert(result, "{")
                table.insert(result, "'"..node.name.."'")
                table.insert(result, ", ")
                
                table.insert(result, "__plume_fdv_" .. macroName .. "_" .. node.name)
                table.insert(result, "}")
                if i < #namedArgs then
                    table.insert(result, ", ")
                end
                
            end
            table.insert(result, "}") -- End of named arguments table.
            table.insert(result, ", ")
            table.insert(result, stringVarargCheckPos)
            table.insert(result, ", ")
            table.insert(result, stringVarargCheckNamed)
        table.insert(result, ")")
        
        return table.concat(result, "")
    end
    
    local function writeValue(node, builder, accName, f, content, isValue, check, checkNil)
        if node.void then
            isValue = true
            accName = "__plume_void"
        end
        if isValue then
            builder:write(node,  accName .. " = " .. content)
        else
            if check then
                content = "__plume_check_concat(" .. content .. ")"
            end
            builder:write(node, f .. "(" .. accName .. ", " .. content .. (checkNil or "") .. ")")
        end
    end
    
    local function getVariableName(node)
        local name = node.content
        for _, index in ipairs(node.sourceToken.index or {}) do
            if index.kind == "INDEX_ACCESS" then
                name = name
                    .. "["
                        .. plume.editLuaCode(index.content)
                    .. "]"
            elseif index.kind == "FIELD_ACCESS" then
                name = name .. "." .. index.content
            end
        end
        return name
    end

    plume.tokenHandlers = {
        -- Blocks
        BLOCK = function(node, builder)
            plume.transpileBlock(node, builder, node.children, node.returnType,
                function(blockAccName)
                    if node.returnType ~= "VALUE" then
                        return "return " .. blockAccName
                    end
                end,
                true -- isFirstBlock
            )
        end,
        
        VOID = function(node, builder)
            plume.transpileBlock(node, builder, node.children, node.returnType,
                function(blockAccName)
                    return "-- void"
                end
            )
        end,

        TEXT = function(node, builder, accName, isValue)
            local text = plume.shortNodeInfos({node})
            writeValue(node, builder, accName, "__plume_buffer_insert", text, isValue)
        end,

        LUA_EXPRESSION = function(node, builder, accName, isValue)
            local code = plume.shortNodeInfos({node}, true)
            writeValue(node, builder, accName, "__plume_buffer_insert", code, isValue, true)
        end,

        VARIABLE = function(node, builder, accName, isValue)
            local variableExpression = plume.getLuaVariableName(node)
            writeValue(node, builder, accName, "__plume_buffer_insert", variableExpression, isValue, true)
        end,

        LIST_ITEM = function(node, builder, accName, isValue, checkNil)
            local short = plume.shortNodeInfos(node.children)
            
            -- Replace nil value by NIL to preserve list size
            if checkNil then
                checkNil = ", true"
            else
                checkNil = ""
            end
                
            if short then
                writeValue(node, builder, accName, "__plume_table_insert", short, isValue, false, checkNil)
            else
                plume.transpileBlock(node, builder, node.children, node.returnType,
                    function(blockAccName)
                        return "__plume_table_insert(" .. accName .. ", " .. blockAccName .. checkNil .. ")"
                    end
                )
            end
        end,
        
        HASH_ITEM = function(node, builder, accName, isValue)
            local short = plume.shortNodeInfos(node.children)
            local name = node.content
            
            local f = "__plume_table_set"
            if node.sourceToken and node.sourceToken.meta then
                f = "__plume_table_metaset"
                name = "__" .. name
            else
                f = "__plume_table_set"
            end
            
            if not (node.sourceToken and node.sourceToken.eval) then
                name = '"' .. name .. '"'
            end
            
            if short then
                builder:write(node, f.."(" .. accName .. ", " .. name .. ", " .. short .. ")")
            else
                plume.transpileBlock(node, builder, node.children, node.returnType,
                    function(blockAccName)
                        return f.."(" .. accName .. ", " .. name .. ", " .. blockAccName .. ")"
                    end
                )
            end
        end,

        ASSIGNMENT = function(node, builder, accName)
            local varName = node.content -- The name of the variable being assigned to.
            local targetVariable

            if node.sourceToken.eval then
                -- If node.sourceToken.eval is true, assign to the global table _G
                -- using varName as a key.
                targetVariable = "_G[" .. varName .. "]"
            else
                targetVariable = varName
            end
            
            if node.sourceToken.index then
                targetVariable = targetVariable .. "[" .. plume.editLuaCode(node.sourceToken.index) .. "]"
            end
            
            local short = plume.shortNodeInfos(node.children, true)
            local compound = node.sourceToken.compound_operator
            
            if short then -- No need to make a block
                local assignment = ""
                if compound then
                    short = targetVariable .. " " .. compound .. " " .. short
                end
                
                if node.islocal then
                    builder:write(node.children[1], "local " .. node.content .. " = " .. short)
                else
                   builder:write(node.children[1], targetVariable .. " = " .. short)
                end
            else
                if node.islocal then
                    builder:write(node, "local " .. node.content)
                end

                plume.transpileBlock(node, builder, node.children, node.returnType,
                    function(blockAccName)
                        if compound then
                            return targetVariable .. " = " .. targetVariable .. node.sourceToken.compound .. blockAccName
                        else
                            return targetVariable .. " = " .. blockAccName
                        end
                    end
                )
            end
        end,

        -- Control structures
        FOR = function(node, builder, accName)
            if node.continue then
                node.continue = builder:getUniqueLabel("FOR")
            end

            --- Temp code, waiting for full script parser ---
            local luaIterator = plume.editLuaCode(node.content)

            -- for ... in ... syntax
            if luaIterator:match('%s+in%s+') then
                local before, after = luaIterator:match('^(.-)%s+in%s+(.-)$')
                luaIterator = before .. " in __plume_iter (" .. after .. ")"
            end
            -------------------------------------------------

            builder:open(node, "for" .. luaIterator .. " do")

            -- Transpile the body of the loop.
            plume.transpileAllToLua(node.children, builder, accName)

            if node.continue then
                builder:write(node, "::" .. node.continue .. "::")
            end

            builder:close(node, "end")
        end,

        WHILE = function(node, builder, accName)
            if node.continue then
                node.continue = builder:getUniqueLabel("WHILE")
            end

            --- Temp code, waiting for full script parser ---
            local luaCondition = plume.editLuaCode(node.content)
            -------------------------------------------------

            builder:open(node, "while" .. luaCondition .. " do")

            -- Transpile the body of the loop.
            plume.transpileAllToLua(node.children, builder, accName)

            if node.continue then
                builder:write(node, "::" .. node.continue .. "::")
            end

            builder:close(node, "end")
        end,

        CONTINUE = function(node, builder, accName)
            builder:write(node, "goto " .. node.loop.continue)
            node.loop = nil -- no need to save the reference in map
        end,
        
        LEAVE = function(node, builder, accName)
            builder:write(node, "goto " .. node.macro.leave)
            node.leave = nil -- no need to save the reference in map
        end,
        
        BREAK = function(node, builder, accName)
            builder:write(node, "break")
        end,
        
        IF = function(node, builder, accName)
            builder:open(node, "if" .. plume.editLuaCode(node.content) .. " then")
            plume.transpileAllToLua(node.children, builder, accName)
            if not node.noend then
                builder:close(node, "end")
            end
        end,
        
        ELSEIF = function(node, builder, accName)
            builder.deep = builder.deep-1
            builder:open(node, "elseif" .. plume.editLuaCode(node.content) .. " then")
            plume.transpileAllToLua(node.children, builder, accName)
            if not node.noend then
                builder:close(node, "end")
            end
        end,


        ELSE = function(node, builder, accName)
            builder.deep = builder.deep-1
            builder:open(node, "else")
            plume.transpileAllToLua(node.children, builder, accName)
            builder:close(node, "end")
        end,
        
        -- Macros
        MACRO_DEFINITION = function(node, builder, accName)
            local macroName
            if node.inline then
                macroName = accName
            else
                macroName = node.content
            end
            
            -- The first child is the parameter list node.
            local parameters = node.children[1]
            -- The second child is the body of the macro.
            local body       = node.children[2]
            
            local positionalArgs, namedArgs, validators, varargPos, varargNamed = readMacroDefinitionParameters(parameters)
            
            for _, node in ipairs(namedArgs) do
                builder:open(node, "local function __plume_fdv_" .. macroName .. "_" .. node.name .. " (__plume_args)")
               plume.transpileBlock(node, builder, node.children, node.returnType,
                    function(blockAccName)
                        return "return " .. blockAccName
                    end,
                    true -- isFirstBlock
                )
                builder:close(node, "end")
            end
            
            if node.inline or node.sourceToken.isLocal then
                builder:open(node, "local function " .. macroName .. "(__plume_args)")
            else
                builder:open(node, "function " .. macroName .. "(__plume_args)")
            end
            
            builder:write(node, makeMacroInit(macroName, positionalArgs, namedArgs, validators, varargPos, varargNamed, node.meta))
            
            for _, info in ipairs(validators) do
                local name      = info[1]
                local validator = info[2]
                local label     = info[3]
                local vararg    = info[4]
                
                local fvalidator = "__plume_validator_" .. info[2]
                
                if not vararg then
                    vararg = 0
                end
                
                -- To enhance error reporting, should use parameters[x] instead of node
                builder:write(node, "__plume_validate(" .. fvalidator .. ", " .. name .. ", '" .. validator .."', '"..label.."', "..vararg..")")
            end
            
            local endLabel
            if node.leave then
                endLabel = builder:getUniqueLabel("macroReturn")
                node.leave = endLabel
            end
            
            plume.transpileBlock(body, builder, body.children, body.returnType,
                function(blockAccName)
                    if body.returnType ~= "VALUE" then
                        return "return " .. blockAccName
                    end
                end,
                true, -- isFirstBlock
                endLabel -- end label
            )
            builder:close(node, "end")
        end,
        
        MACRO_CALL = function(node, builder, accName, isValue)
            local argName     = "__plume_args_" .. builder.deep
            local argTable    = node.children[1]
            local argTableExt = node.children[2]
            
            -- Check for several argument with the same name
            local names = {}
            
            for _, arg in ipairs((argTable or {}).children or {}) do
                if arg.kind == "HASH_ITEM" then
                    if names[arg.content] then
                        plume.multipleArgumentSameName (node.sourceToken.source, arg.content)
                    else
                        names[arg.content] = true
                    end
                end
            end
            for _, arg in ipairs((argTableExt or {}).children or {}) do
                if arg.kind == "HASH_ITEM" then
                    if names[arg.content] then
                        plume.multipleArgumentSameName (node.sourceToken.source, arg.content)
                    else
                        names[arg.content] = true
                    end
                end
            end
        
            -- init args table
            builder:write(node, "local " .. argName .. " = __plume_table()")
            
            -- add args
            local argCount = 0
            for _, child in ipairs(argTable.children) do
                plume.tokenHandlers[child.kind] (child, builder, argName, false, true)
            end
            if argTableExt then
                if argTableExt.returnType == "TEXT" or argTableExt.returnType == "VALUE" then
                    plume.tokenHandlers.LIST_ITEM (argTableExt, builder, argName, false, true)
                else
                    for _, child in ipairs(argTableExt.children) do
                        plume.tokenHandlers[child.kind] (child, builder, argName, false, true)
                    end
                end
            end
            
            local name = getVariableName(node)
            local tableName, methodName = name:match("^(.-)%.([^%.]+)$")
            if tableName then
                builder:write(node, "__plume_table_set(" .. argName .. ", \"self\", " .. tableName .. ")")
            end
            
            -- call and add to buffer
            if isValue then
                builder:write(node, accName .. " = " .. name .. "(" .. argName .. ")")
            elseif node.void then
                builder:write(node, name .. "(" .. argName .. ")")
            elseif node.expandList then
                builder:write(node, "__plume_expand_list(" .. accName .. ", " .. name .. "(" .. argName .. "))")
            elseif node.expandHash then
                builder:write(node, "__plume_expand_hash(" .. accName .. ", " .. name .. "(" .. argName .. "))")
            else
                builder:write(node, "__plume_buffer_insert(" .. accName .. ", __plume_check_concat(" .. name .. "(" .. argName .. ")))")
            end
        end,
        
        -- Expand
        COMMAND_EXPAND_LIST = function(node, builder, accName)
            local name = getVariableName(node)
            builder:write(node, "__plume_expand_list(" .. accName .. ", " .. name .. ")")
        end,
        
        COMMAND_EXPAND_HASH = function(node, builder, accName)
            local name = getVariableName(node)
            builder:write(node, "__plume_expand_hash(" .. accName .. ", " .. name .. ")")
        end,
        
        -- Others
        RETURN = function(node, builder, accName)
            plume.transpileBlock(node, builder, node.children, node.returnType,
                function(blockAccName)
                    return "return " .. blockAccName
                end
            )
        end
    }
end